use_frameworks!

target 'SubspecTest_Example', :exclusive => true do
  pod 'SubspecTest/Main', :path => '../'
end

target 'SubspecTest_Tests', :exclusive => true do
  pod 'SubspecTest/Sub1', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
end
